# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0580b040631f384ca7f08a1bb90b692"
name = "growing-deal-app"
handle = "growing-deal-app"
application_url = "https://copies-human-louisiana-standard.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "centranage.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://copies-human-louisiana-standard.trycloudflare.com/auth/callback",
  "https://copies-human-louisiana-standard.trycloudflare.com/auth/shopify/callback",
  "https://copies-human-louisiana-standard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
